import { BugIcon } from '@primer/octicons-react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <BugIcon size="20" />
      </main>
    </div>
  )
}
